version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xJt83wCpHf82F2
      - MYSQL_DATABASE=homedb
    ports:
      - "3307:3306"
    
  springboot-docker-container:
    image: docker-spring-boot-project-example
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/my_db_springboot?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "xJt83wCpHf82F2"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
